// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hello_world.proto
// Protobuf Java Version: 4.27.2

package com.sunpe.mygrpc.example.proto.helloworld;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
