// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: health.proto
// Protobuf Java Version: 4.27.3

package com.sunpe.mygrpc.base.health;

public interface HealthCheckRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.health.v1.HealthCheckRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service = 1;</code>
   * @return The service.
   */
  java.lang.String getService();
  /**
   * <code>string service = 1;</code>
   * @return The bytes for service.
   */
  com.google.protobuf.ByteString
      getServiceBytes();
}
